src/components/log.vue, src/components/projects.vue, src/components/runs.vue, src/components/runsummary.vue, src/components/tasksummary.vue, src/util/auth.js, src/util/data.js, src/views/Oauth2.vue, src/views/Project.vue, src/views/User.vue
* Use AbortController to signal fetch to stop when component is destroyed
* Remove polling and just schedule a new fetch at the end of the current one
when not aborted.
=> *: abort async fetch on component destroy

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/support.md
=> Add github issue templates

src/components/log.vue
* show a spinner while log is being fetched: while calling the api and while
streaming the log
* show when log doesn't exists
* show error when fetching the log fails (with retry button)
* show when there're no lines.
resolves #24
=> log: show log fetching status

src/views/Login.vue, src/views/Register.vue
Show if no remote sources are defined or if no remote sources are register/login
enabled.
=> register/login: display if there are no remote sources

babel.config.js, package-lock.json, package.json, src/components/tasksgraph.vue, src/util/auth.js, tailwind.js
* fix newer lint errors
* tailwindcss: disable use of system ui sans font
=> npm: update dependencies

src/util/auth.js
Related agola PR: https://github.com/agola-io/agola/pull/215
=> auth: update auth api paths

src/components/createsourceform.vue, src/router.js, src/util/auth.js, src/util/data.js, src/views/CreateSource.vue, src/views/Login.vue, src/views/Register.vue
It probably needs some improvements and I probably made a few grammar errors
One of the commits updated the package-lock.json. I can revert it if necessary.
=> Add "create remote source" page

src/components/log.vue
Creating group of N log lines inside their own div will make the rendering faster.
We could also use an intersection observer to only render visible groups but this will break searching using browser searching since it won't find data inside not rendered groups and will require a custom searching entry.
=> log: improve rendering performance

.agola/config.jsonnet, package.json, pnpm-lock.yaml
- regenerates the pnpm.lock file
- fixes the pnpm version to `^8`
=> npm: regenerate the pnpm.lock file and lock the pnpm version

src/App.vue
=> topbar: Add home menu item to the main menu.

src/app/api.ts, src/components/userorgs.vue, src/router/index.ts, src/util/link.ts, src/views/User.vue
=> user: add "Organizations" tab to user's home page.

src/app/api.ts, src/components/orgmembers.vue
Implement new agola backend cursor based list api for GetOrgMembers.
To be merged just after https://github.com/agola-io/agola/pull/436
=> api: use cursor based GetOrgMembers api

src/components/delay.vue, src/components/orgmembers.vue, src/main.ts
* add a delay wrapper component to show the content after a specified
timeout.
* Add a loading spinner after 500ms delay.
* Don't show load more when loading
=> orgmembers: add loading spinner and improve behavior

src/app/api.ts, src/components/userorgs.vue
Implement new agola backend cursor based list api for GetUserOrgs.
To be merged just after agola-io/agola#439
=> api: use cursor based GetUserOrgs api

src/app/api.ts, src/components/createproject.vue, src/components/usersettings.vue, src/util/remotesource.ts, src/views/AddLinkedAccount.vue, src/views/Login.vue, src/views/Register.vue
Implement new agola backend cursor based list api for GetRemoteSources.
To be merged just after agola-io/agola#440
=> api: use cursor based GetRemoteSources api

.agola/config.jsonnet, Dockerfile, package.json, pnpm-lock.yaml, src/components/projectsettings.test.ts, src/components/projectsettings.vue, tests/setup-router-mock.ts, vite.config.ts
* Add mock service worker to mock http requests
* Add initial tests for projectsettings component as a starting point for following ones.
=> *: Add initial component tests (projectsettings)

src/app/api.ts, src/components/createupdatesecret.test.ts, src/components/createupdatesecret.vue, src/components/projectgroupsettings.vue, src/components/projectsecrets.vue, src/components/projectsettings.vue, src/components/secrets.test.ts, src/components/secrets.vue, src/router/index.ts, src/util/link.ts, src/util/twind.ts, src/util/validator.ts
=> *: implement secret create/update/delete

src/app/api.ts, src/components/runs.test.ts, src/components/runs.vue
Implement new agola backend cursor based list api for GetRuns.
To be merged just after https://github.com/agola-io/agola/pull/484
=> api: use cursor based GetRuns api

src/components/createupdatesecret.vue, src/components/projectsecrets.vue, src/util/twind.ts
When possible use btn custom twind classes.
=> *: use btn classes

src/components/createupdatesecret.vue
Add labels to input fields and update placeholders names.
=> createupdatesecret: add input labels

src/components/modals/confirmationDialog.vue, src/components/projectgroupsettings.vue, src/components/projectsecrets.vue, src/components/projectsettings.vue, src/components/secrets.test.ts, src/components/secrets.vue
Use better emits names and define them.
Use better variables/function names.
Style cleanup: missing new lines, functions order etc...
=> *: clean project secrets components

src/app/api.ts, src/components/createupdatevariable.test.ts, src/components/createupdatevariable.vue, src/components/projectgroupsettings.vue, src/components/projectsettings.vue, src/components/projectvars.vue, src/components/vars.vue, src/router/index.ts, src/util/link.ts
=> ui: create delete variables

src/components/createproject.test.ts, src/components/createproject.vue, src/components/createprojectgroup.test.ts, src/components/createprojectgroup.vue, src/components/createupdatesecret.test.ts, src/components/createupdatevariable.test.ts, src/components/projectgroupsettings.test.ts, src/components/projectgroupsettings.vue, src/components/projectsettings.test.ts, src/components/projectsettings.vue, src/components/secrets.test.ts, src/util/validator.test.ts
Add name validation to project/projectgroup create and settings.
Update tests to cover the related components.
=> project/projectgroup: add name validation

src/app/api.ts, src/app/auth.ts, src/components/createorganization.vue, src/components/createproject.vue, src/components/createprojectgroup.vue, src/components/createupdatesecret.vue, src/components/createupdatevariable.vue, src/components/log.vue, src/components/orgmembers.vue, src/components/projectgroupsettings.vue, src/components/projects.vue, src/components/projectsettings.vue, src/components/rundetail.vue, src/components/runs.vue, src/components/runsummary.vue, src/components/secrets.vue, src/components/tasksummary.vue, src/components/userorgs.vue, src/components/usersettings.vue, src/components/vars.vue, src/router/index.ts, src/views/AddLinkedAccount.vue, src/views/CreateSource.vue, src/views/Login.vue, src/views/Project.vue, src/views/Register.vue, src/views/User.vue
use custom APIAbortedError instead of an APIError with a custom field to record if aborted.
Also rename ApiError to APIError.
=> api: use custom APIAbortedError

src/app/api.ts, src/app/auth.ts, src/components/createupdatesecret.test.ts, src/components/createupdatesecret.vue, src/components/createupdatevariable.test.ts, src/components/createupdatevariable.vue
Handle api error details by returning an human readable error string based on the api error details codes.
=> api: handle api error details

src/App.vue
Wait for auth to have finished trying fetching the current user before showin login/register buttons.
=> App: show login/register only if auth is ready
